name: Create a stable release
on:
  push:
    tags:
       - '*'
  pull_request:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish Enmity for iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          submodules: true

      - name: Check cache
        id: verify-cache
        run: |
          echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1`"

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ steps.verify-cache.outputs.heads }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Prepare Azule
        run : |
          git clone https://github.com/Al4ise/Azule ${{ github.workspace }}/Azule

      - name: Prepare Enmity Patcher
        run : |
          curl -L https://github.com/enmity-mod/patcher/releases/latest/download/patcher.mac-amd64 -o ${{ github.workspace }}/patcher
          chmod +x patcher

      - name: Patch Discord
        run : |
          ${{ github.workspace }}/patcher

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1

      - name: Find deb
        id: find_deb
        run : |
          echo "::set-output name=deb::$(find packages -name "*.deb" -print -quit)"
          mv $(find packages -name "*.deb" -print -quit) Enmity.deb

      - name: Create Enmity.ipa
        run : |
          mkdir out
          ${{ github.workspace }}/Azule/azule -i Enmity.ipa -o out -f Enmity.deb
          mv $(find out -name "*.ipa" -print -quit) out/Enmity.ipa

      - name: Build dev deb
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 DEVTOOLS=1

      - name: Find dev deb
        id: find_deb_dev
        run : |
          echo "::set-output name=deb::$(find packages -name "*.deb" -print -quit)"
          mv $(find packages -name "*.deb" -print -quit) Enmity.Dev.deb

      - name: Create Enmity.Dev.ipa
        run : |
          ${{ github.workspace }}/Azule/azule -i Enmity.Dev.ipa -o out -f Enmity.Dev.deb
          mv $(find out -name "*.Dev.ipa" -print -quit) out/Enmity.Dev.ipa

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.ref_name }}
          files:  |
            Enmity.deb
            Enmity.Dev.deb
            out/Enmity.ipa
            out/Enmity.Dev.ipa
